export let tickets_dev = [
  {
    nombre: "María García",
    telefono: "555-5678",
    correo: "mariagarcia@email.com",
    titulo: "",
    descripcion: "El sistema de banca en línea está mostrando un mensaje de error.",
    fecha_y_hora: "2024-05-18 09:15 AM",
    ubicacion: "Acceso desde navegador web",
    identificador: "(Problema de servidor)",
    responsable: "Equipo de Soporte Banca en Línea",
    impacto_en_el_negocio: "Alto",
    tipo_de_incidencia: "Software",
    priorizacion: "Alto",
    estado: "En curso",
    causas: "Error en la comunicación con la base de datos del servidor.",
    reporte: "El usuario reporta mensaje de error al intentar acceder a su cuenta en línea.",
    resolucion: "Se reinició el servidor de la base de datos y se restableció la conexión. Se monitorea el sistema para asegurar la estabilidad."
  },
  {
    nombre: "Sofía Gómez",
    telefono: "555-3344",
    correo: "sofiagomez@email.com",
    titulo: "",
    descripcion: "El sistema de banca en línea está mostrando un mensaje de error.",
    fecha_y_hora: "2024-12-10 09:15 AM",
    ubicacion: "Oficina de Créditos, Estación #12",
    identificador: "EST-CRE-12",
    responsable: "Equipo de Soporte Redes",
    impacto_en_el_negocio: "Alto",
    tipo_de_incidencia: "Red",
    priorizacion: "Medio",
    estado: "Cerrado",
    causas: "Interrupción temporal del servicio de internet en la sucursal.",
    reporte: "Personal de la oficina reporta la imposibilidad de acceder al sistema en línea. Se verifica la conexión de red local.",
    resolucion: "Se contactó al proveedor de internet y se restableció la conexión. Se verificó el acceso al sistema."
  },
  {
    nombre: "Pedro Vargas",
    telefono: "555-3344",
    correo: "pedrovargas@email.com",
    titulo: "Cargos no reconocidos en mi estado de cuenta",
    descripcion: "He detectado dos cargos en mi estado de cuenta que no reconozco haber realizado. Necesito información sobre estos movimientos.",
    fecha_y_hora: "2024-05-08 01:30 PM",
    ubicacion: "Revisión desde mi dispositivo móvil",
    identificador: "EAT-CRE-12",
    responsable: "Equipo de Soporte Redes",
    impacto_en_el_negocio: "Alto",
    tipo_de_incidencia: "Software",
    priorizacion: "Alto",
    estado: "En curso",
    causas: "Investigando posible fraude o error en el procesamiento de transacciones.",
    reporte: "Cliente reporta cargos no reconocidos en su estado de cuenta. Se solicita revisión de los registros de transacciones.",
    resolucion: "En investigación. Se contactará al cliente con los hallazgos y los pasos a seguir."
  },
  {
    nombre: "Laura Torres",
    telefono: "555-8899",
    correo: "lauratorres@email.com",
    titulo: "Tarjeta de crédito bloqueada sin notificación",
    descripcion: "Mi tarjeta de crédito fue bloqueada y no recibí ninguna notificación previa. Necesito saber el motivo y cómo desbloquearla.",
    fecha_y_hora: "2024-05-08 02:00 PM",
    ubicacion: "Intento de pago en supermercado",
    identificador: "EAT-CRE-12",
    responsable: "Equipo de Soporte Redes",
    impacto_en_el_negocio: "Alto",
    tipo_de_incidencia: "Red",
    priorizacion: "Medio",
    estado: "Cerrado",
    causas: "Bloqueo preventivo por actividad sospechosa detectada por el sistema de seguridad.",
    reporte: "Cliente reporta bloqueo de tarjeta al intentar realizar un pago. No recibió notificación previa del bloqueo.",
    resolucion: "Se verificó la actividad sospechosa y se confirmó el bloqueo preventivo. Se contactó a la cliente para verificar su identidad y se procedió al desbloqueo de la tarjeta."
  }
]